import Head from 'next/head';
import Link from 'next/link';
import { useState } from 'react';
import React from 'react';

export default function Manage() {
  const [empNo, setEmpNo] = useState('');
  const [empName, setEmpName] = useState('');
  const [content, setContent] = useState('');
  const [visible, setVisible] = useState(true);

  const onChangeAdd = () => {};
  return (
    <>
      <Head>
        <title>fot unit test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h3> Sample </h3>
      </div>
      <div style={{ alignContent: 'center' }}>
        <div style={{ margin: '10px 0 15px 0' }}>
          <label style={{ marginRight: '10px' }}>Employee Number</label>
          <input
            type="text"
            required
            id="empNo"
            maxLength={5}
            value={empNo}
            onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
              setVisible(false);
              setEmpNo(e.target.value);
            }}
          />
        </div>
        <div style={{ margin: '3px 0 15px 0' }}>
          <label style={{ marginRight: '25px' }}>Employee Name</label>
          <input
            type="text"
            required
            id="empName"
            value={empName}
            maxLength={15}
            onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
              setEmpName(e.target.value);
              setVisible(false);
            }}
          />
        </div>
        <div style={{ marginBottom: '15px' }}>
          <label style={{ marginRight: '86px' }}>Content</label>
          <input
            type="text"
            id="content"
            value={content}
            onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
              setContent(e.target.value);
              setVisible(false);
            }}
          />
        </div>
        <div style={{ margin: '5px 0 0 120px' }}>
          <button id={'btnAdd'} onClick={onChangeAdd} disabled={visible}>
            Add
          </button>
        </div>
      </div>
      <Link href="/" style={{ color: 'purple', fontWeight: 'bold' }}>
        Back To Home
      </Link>
    </>
  );
}
