import Footer from '@/app/components/footer/footer';
import Header from '@/app/components/header/header';
import type { Metadata } from 'next';
import React from 'react'; // Import React to fix the 'React' must be in scope when using JSX error

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
